# lightning.pytorch==2.0.6
model: &model mt5
seed_everything: true

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: eval/accumulate
        min_delta: 0.0001
        patience: 35
        verbose: false
        mode: max
        check_finite: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: eval/accumulate
        mode: max
        dirpath: checkpoints/ # how to set the right folder?
        filename: best
        save_on_train_epoch_end: false
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        name: run_name
        save_dir: wandb_dir/run_name
        project: wandb_project_name

  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: false
  profiler: null
  detect_anomaly: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  model_name: *model
  tasks: null
  batch_name_map_eval: null
  batch_name_map_test: null
  label2id: null
  peft: false
  peft_checkpoint: false
  num_accum_batches: 1
  r3f: false
  r4f: false
  scale_loss: false
  retain_grads: false
data:
  model_name: *model
  size: null
  to_text: true
  task_names: [paws-x]
  t: 1
  batch_size: 16
  distributed: false
  max_length_padding: 512
  mix_mlm: false
  zero_shot_ctk: false
  heterogenous_distributed: false
  insert_prefix: true
  init_seed: 42
  mlm_prob: 0.01
# ckpt_path: "checkpoints/xlm-r-2/"
